Milestone 9: Css
Lizdev-05/My-blog pull request #11
Opened 2022-11-01 20:39 UTC by Lizdev-05

I used Capybara to write integration tests for each view in your project. I tested...

- User index page
- user show page
- User post index page
- Post-show page

2022-11-01 22:13 UTC, tufoinnkuo10 requested changes
Hi @Lizdev-05 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ Test ok
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-01 22:13 UTC, tufoinnkuo10 commented on spec/views/user_index_spec.rb
> +    it "renders the user's last 3 posts" do
- [ ] Renders user first 3 post not last. kindly corrrect that

2022-11-01 22:13 UTC, tufoinnkuo10 commented on spec/views/user_index_spec.rb
> +  describe 'show page' do
- [ ] please the Spec file should only test User index page. the below test for show page should be in its own spec file

2022-11-01 22:13 UTC, tufoinnkuo10 commented on spec/views/user_show_spec.rb
> +
- [ ] Great job. you are missing Tests that asserts you can see a button that lets you view all of a user's posts

2022-11-01 22:13 UTC, tufoinnkuo10 commented on spec/views/post_show_spec.rb
> +
- [ ] Please add Tests that asserts you can see who wrote the post.

2022-11-01 22:13 UTC, tufoinnkuo10 commented on spec/views/post_index_spec.rb
> +  describe 'show page' do
- [ ] The post show page is already tested in its own spec file so its not necesary doing it all over again here. great work

2022-11-01 23:49 UTC, Lizdev-05 commented on spec/views/user_index_spec.rb
> +    it "renders the user's last 3 posts" do
Thank you for reviewing and correcting my work,. It is not supposed to be the first 3 posts though, but the last ones. the last ones are the recent ones.  I have renamed it to fit the content more though. thank you

2022-11-01 23:49 UTC, Lizdev-05 commented on spec/views/user_index_spec.rb
> +  describe 'show page' do
Done

2022-11-01 23:50 UTC, Lizdev-05 commented on spec/views/user_show_spec.rb
> +
It is already there, it tests the route_path. Kindly check again

2022-11-01 23:51 UTC, Lizdev-05 commented on spec/views/post_show_spec.rb
> +
I have a test that confirms the post author, kindly check it well.

2022-11-01 23:51 UTC, Lizdev-05 commented on spec/views/post_index_spec.rb
> +  describe 'show page' do
Okay.

2022-11-02 00:14 UTC, descholar-ceo approved these changes
Hi @Lizdev-05 🤝  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all of the requested changes ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 00:31 UTC, merged